---
# - name: Lookup 
#   ansible.builtin.debug:
#     msg: "{{ hostvars[inventory_hostname]['bridge']['vlan'] | selectattr('vlanid','ne', 100) | length }}"
#   loop: "{{ hostvars[inventory_hostname]['bridge']['vlan'] }}"
#   when: '100' in "{{ hostvars[inventory_hostname]['bridge']['vlan'] | json_query('[].vlanid') }}"

- name: Set device hostname
  community.routeros.api_modify:
    hostname: "{{ address }}"
    password: "{{ ros_api_password }}"
    username: "{{ ros_api_user }}"
    path: system identity
    data:      
      - name: "{{ inventory_hostname }}"
      
- name: Get VLAN Info
  community.routeros.api_info:
    hostname: "{{ address }}"
    password: "{{ ros_api_password }}"
    username: "{{ ros_api_user }}"
    path: interface bridge vlan
  register: interface_bridge_vlan

# - name: Print VLANs
#   ansible.builtin.debug:
#     var: interface_bridge_vlan

- name: Create VLANs
  loop: "{{ hostvars[inventory_hostname]['bridge_vlan'] }}"
  # Создаем VLAN только если его нет в списке VLAN, полученном с устройства
  when: interface_bridge_vlan.result | selectattr('vlan-ids','eq',item.vlanid) | length == 0
  community.routeros.api_modify:
    hostname: "{{ address }}"
    password: "{{ ros_api_password }}"
    username: "{{ ros_api_user }}"
    path: interface bridge vlan
    data:      
      - vlan-ids: "{{ item.vlanid }}"
        comment: "{{ item.comment }}"
        bridge: "{{ hostvars[inventory_hostname]['bridge'].name }}"

- name: Prepare VLAN entries accumulated
  set_fact:
    vlan_entries: "{{ vlan_entries | default([]) + [{'bridge': bridge.name, 'vlan-ids': item.vlanid, 'comment': item.comment}] }}"
  loop: "{{ bridge_vlan }}"

- name: Update VLAN settings with single api_modify call
  community.routeros.api_modify:
    hostname: "{{ address }}"
    password: "{{ ros_api_password }}"
    username: "{{ ros_api_user }}"
    path: interface bridge vlan
    data: "{{ vlan_entries }}"

- name: Get bridge port info
  community.routeros.api_info:
    hostname: "{{ address }}"
    password: "{{ ros_api_password }}"
    username: "{{ ros_api_user }}"
    path: interface bridge port
  register: interface_bridge_port
  tags:
    - bridge-port

- name: Add ports to bridge
  loop: "{{ hostvars[inventory_hostname]['bridge_port'] }}"
  # Добавляем порт в bridge только если его нет в нем
  when: >- 
    (interface_bridge_port.result
    | selectattr('bridge','eq',hostvars[inventory_hostname]['bridge'].name)
    | selectattr('interface','eq',item.name) | length) == 0
  community.routeros.api_modify:
    hostname: "{{ address }}"
    password: "{{ ros_api_password }}"
    username: "{{ ros_api_user }}"
    path: interface bridge port
    # restrict directive available since v.2.18 of community.routeros
    # restrict:
    #   - field: bridge
    #     values:
    #       - "{{ hostvars[inventory_hostname]['bridge'].name }}"
    #     invert: true
    data:      
      - interface: "{{ item.name }}"
        pvid: "{{ item.pvid }}"
        comment: "{{ item.comment }}"
        bridge: "{{ hostvars[inventory_hostname]['bridge'].name }}"
  tags:
    - bridge-port

# Получаем обновленные параметры портов в bridge
# Пропускать, если новые порты не были добавлены в bridge, нельзя т.к. на выходе получим пустую
# переменную interface_bridge_port.
- name: Get bridge port info
  community.routeros.api_info:
    hide_defaults: false
    hostname: "{{ address }}"
    password: "{{ ros_api_password }}"
    username: "{{ ros_api_user }}"
    path: interface bridge port
  register: interface_bridge_port
  tags:
    - bridge-port

# - name: Print bridge port
#   ansible.builtin.debug:
#     var: interface_bridge_port
#   tags:
#     - bridge-port

- name: Update bridge port settings
  loop: "{{ hostvars[inventory_hostname]['bridge_port'] }}"
  when: >- 
    (interface_bridge_port.result
    | selectattr('bridge','eq',hostvars[inventory_hostname]['bridge'].name)
    | selectattr('interface','eq',item.name) 
    | selectattr('pvid','eq',item.pvid) 
    | selectattr('comment','eq',item.comment) | length) == 0
  community.routeros.api_find_and_modify:
    hostname: "{{ address }}"
    password: "{{ ros_api_password }}"
    username: "{{ ros_api_user }}"
    path: interface bridge port
    find:
      interface: "{{ item.name }}"
      bridge: "{{ hostvars[inventory_hostname]['bridge'].name }}"
    values:      
      pvid: "{{ item.pvid }}"
      comment: "{{ item.comment }}"        
  tags:
    - bridge-port

- name: Get physical interface info
  community.routeros.api_info:
    hostname: "{{ address }}"
    password: "{{ ros_api_password }}"
    username: "{{ ros_api_user }}"

    path: interface ethernet
  register: interface_ethernet
  tags:
    - bridge-port
# - name: Print physical interfaces
#   ansible.builtin.debug:
#     var: interface_ethernet
#   tags:
#     - bridge-port

- name: Initialize interface comments update list
  set_fact:
    interface_comments_update: []
  tags:
    - bridge-port

- name: Prepare interface comments update data with default-name
  set_fact:
    interface_comments_update: "{{ interface_comments_update + [{
        'default-name': item.name,
        'comment': item.comment
      }] }}"
  loop: "{{ hostvars[inventory_hostname]['bridge_port'] }}"
  when: item.name is defined and item.comment is defined

- name: Update physical interfaces comments
  community.routeros.api_modify:
    hostname: "{{ address }}"
    password: "{{ ros_api_password }}"
    username: "{{ ros_api_user }}"
    path: interface ethernet
    data: "{{ interface_comments_update }}"
    
- name: Set VLAN tagged ports
  loop: "{{ hostvars[inventory_hostname]['bridge_vlan'] }}"
  community.routeros.api_find_and_modify:
    hostname: "{{ address }}"
    password: "{{ ros_api_password }}"
    username: "{{ ros_api_user }}"
    ignore_dynamic: true
    path: interface bridge vlan
    find: >-
      {{
        dict([
          ['bridge', hostvars[inventory_hostname]['bridge'].name],
          ['vlan-ids', item.vlanid]
        ])

      }}      
    values:
      tagged: "bridge,{{ hostvars[inventory_hostname]['bridge_port'] | selectattr ('tagged','defined') | selectattr ('tagged','contains',item.vlanid) | map(attribute='name') | join(',') }}"
  tags:
    - bridge-port

- name: Set loop-protect
  block:
    - name: Build loop-protect data
      set_fact:
        routeros_loop_protect_data: "{{ routeros_loop_protect_data | default([]) + [ {
          'default-name': item.name,
          'loop-protect': (
            'on' if item.get('loop-protect') is sameas true
            else 'off' if item.get('loop-protect') is sameas false
            else 'default'
          )
        } ] }}"
      loop: "{{ hostvars[inventory_hostname]['bridge_port'] }}"

    - name: Apply loop-protect once
      community.routeros.api_modify:
        hostname: "{{ address }}"
        username: "{{ ros_api_user }}"
        password: "{{ ros_api_password }}"
        path: interface ethernet
        data: "{{ routeros_loop_protect_data }}"

- name: Set edge
  block:
    - name: Build edge data
      set_fact:
        routeros_edge_data: "{{ routeros_edge_data | default([]) + [ {
          'interface': item.name,
          'bridge': hostvars[inventory_hostname].bridge.name,
          'edge': (
            'yes' if item.get('loop-protect') is sameas true
            else 'no' if item.get('loop-protect') is sameas false
            else 'auto'
          )
        } ] }}"
      loop: "{{ hostvars[inventory_hostname]['bridge_port'] }}"
    
    - name: Apply edge settings
      community.routeros.api_modify:
        hostname: "{{ address }}"
        username: "{{ ros_api_user }}"
        password: "{{ ros_api_password }}"
        path: interface bridge port
        data: "{{ routeros_edge_data }}"

- name: Set storm rate
  block:
    - name: Get all ethernet switch ports
      community.routeros.api_info:
        hostname: "{{ address }}"
        password: "{{ ros_api_password }}"
        username: "{{ ros_api_user }}"
        path: interface ethernet switch port
      register: storm_all_device_ports

    - name: Get bridge members
      community.routeros.api_info:
        hostname: "{{ address }}"
        password: "{{ ros_api_password }}"
        username: "{{ ros_api_user }}"
        path: interface bridge port
      register: storm_all_bridge_ports

    - name: Create list of bridge member interfaces
      set_fact:
        bridge_member_interfaces: "{{ storm_all_bridge_ports.result | selectattr('bridge', 'equalto', hostvars[inventory_hostname].bridge.name) | map(attribute='interface') | list }}"

    - name: Build storm rate configuration data
      set_fact:
        storm_rate_data: "{{ storm_rate_data | default([]) + [ {
          'name': item,
          'limit-unknown-multicasts': 'yes' if item in bridge_member_interfaces else 'no',
          'limit-unknown-unicasts': 'yes' if item in bridge_member_interfaces else 'no',
          'storm-rate': 5 if item in bridge_member_interfaces else 100
        } ] }}"
      loop: "{{ storm_all_device_ports.result | map(attribute='name') | list }}"

    # - name: Print storm_rate_data
    #   ansible.builtin.debug:
    #     var: storm_rate_data
    
    - name: Apply storm protect configuration
      community.routeros.api_modify:
        hostname: "{{ address }}"
        password: "{{ ros_api_password }}"
        username: "{{ ros_api_user }}"
        path: interface ethernet switch port
        data: "{{ storm_rate_data }}"


- name: Set speed on interfaces
  block:
    - name: Set speed 100Mb/s
      community.routeros.api_find_and_modify:
        hostname: "{{ address }}"
        password: "{{ ros_api_password }}"
        username: "{{ ros_api_user }}"
        path: interface ethernet
        find:
          name: "{{ item.name }}"
        values:
          advertise:
            '10M-baseT-half,10M-baseT-full,100M-baseT-half,100M-baseT-full'
          # - '1G-baseT-half'
          # - '1G-baseT-full'
      loop: "{{ hostvars[inventory_hostname]['bridge_port'] | selectattr('speed', 'defined') | selectattr('speed','equalto',100) }}"